
    SELECT  (PCPEDIFV.QT * PCPEDIFV.PVENDA) VL_VENDA_PERDIDA
           ,PCPEDIFV.CODPROD
           ,PCPRODUT.DESCRICAO
           ,PCPEDIFV.QT
           ,PCPEDIFV.PVENDA
           ,PCPEDIFV.CODAUXILIAR
           ,PCPEDIFV.CODFILIALRETIRA
           ,PCPEDIFV.OBSERVACAO_PC
         --  ,translate(PCPEDIFV.OBSERVACAO_PC,'
    --‚‡„·¡¬¿√ÈÍ… ÌÕÛÙı”‘’¸˙‹⁄«Á',' AAAAAAAAEEEEIIOOOOOOUUUUCC') OBSERVACAO_PC
    
           ,PCPEDIFV.NUMPEDRCA
           ,PCPEDIFV.DTINCLUSAO
           ,PCPEDIFV.CODUSUR
           ,PCPEDIFV.QT_FATURADA
           ,PCPEDIFV.DTABERTURAPEDPALM
           ,PCPEDIFV.CGCCLI
           ,PCPEDIFV.UNIDADE_FRIOS
           ,PCPEDIFV.BONIFIC
           ,PCPEDIFV.CODCOMBO
           ,PCPEDIFV.POLITICAPRIORITARIA
           ,PCPEDIFV.DTALTERACAO
           ,PCPEDIFV.PERCDESCEDI
           ,PCPEDIFV.CODMOTIVONAOATEND
           ,PCPEDIFV.PERDESCBOLETO
           ,PCPEDIFV.CODPRODOL
           ,PCPEDIFV.CORTE
           ,PCPEDIFV.SUGESTAO
           ,PCPEDIFV.TIPOENTREGA
           ,PCPEDIFV.NUMPED
           ,PCPEDIFV.RESTRICAOTRANSP 
      FROM PCPRODUT, PCPEDIFV
     WHERE (1 = 1 
       AND PCPRODUT.CODPROD = PCPEDIFV.CODPROD 
      --- AND TRUNC(PCPEDIFV.DTINCLUSAO) BETWEEN :DTINICIO AND :DTFINAL 
      -- AND PCPEDIFV.CODUSUR = :CODUSUR
       AND PCPEDIFV.NUMPEDRCA = 4200009149) AND NUMPEDRCA = 4200009149  
     ORDER BY PCPRODUT.CODPROD