SELECT 
       PCPEDI.CODCLI,
       PCPEDI.CODPROD,
       PCPRODUT.DESCRICAO,
     
       PCPEDI.QT,
       PCPEDI.PVENDA,
       PCEST.CUSTOULTENT,
    
        ROUND(((PCPEDI.PVENDA / PCEST.CUSTOULTENT)*100 ) -100,2) || '%'
  FROM PCPEDI, PCEST, PCPRODUT
 WHERE NUMPED = 1002433
 AND PCPRODUT.CODPROD = PCPEDI.CODPROD
 AND PCPRODUT.CODPROD = PCEST.CODPROD
 AND PCEST.CODFILIAL = 1 
 AND PCEST.CODPROD = PCPEDI.CODPROD 
