SELECT NVL(VENDAS.CODPRACA, DEVOLUCAO.CODPRACA) CODPRACA,
                  NVL(VENDAS.PRACA, DEVOLUCAO.PRACA) PRACA,
                  SUM(DISTINCT(VENDAS.QTCLIPOS)) QTCLIPOS,
                  SUM(NVL(VENDAS.QTVENDA, 0) - NVL(DEVOLUCAO.QTDEVOLUCAO, 0)) QTVENDA,
                  SUM(NVL(VENDAS.VLVENDA, 0) - NVL(DEVOLUCAO.VLDEVOLUCAO, 0)) VLVENDA,
                  SUM(NVL(DEVOLUCAO.VLDEVOLUCAO, 0)) VLDEVOLUCAO,
                  SUM(NVL(VENDAS.TOTPESO, 0) - NVL(DEVOLUCAO.TOTPESO, 0)) TOTPESO
FROM (SELECT CODPRACA,  PRACA,
               COUNT(DISTINCT(QTCLIPOS)) QTCLIPOS,
               SUM(NVL(QTVENDA, 0)) QTVENDA,
               SUM(NVL(VLVENDA, 0) + NVL(VALORST, 0) + NVL(VALORIPI, 0)) VLVENDA,
               SUM(NVL(TOTPESO, 0)) TOTPESO
FROM (SELECT PCNFSAID.CODPRACA, PCPRACA.PRACA,         
       ROUND((NVL(PCMOV.QT, 0) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.VLIPI, 0)))),2) VALORIPI,
       ROUND(NVL(PCMOV.QT, 0) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,(nvl(pcmov.ST, 0) + NVL(PCMOVCOMPLE.VLSTTRANSFCD, 0)))),2) VALORST,
       ((DECODE(PCMOV.CODOPER,'S',(NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'SM',
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'ST',
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'SB',
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),0))) QTVENDA,
 CASE
         WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM, 0) <> 0 THEN
            DECODE(NVL(PCMOV.TIPOITEM, 'N'),'I',0,NVL(PCMOVCOMPLE.VLSUBTOTITEM, 0) +
           (DECODE(NVL(PCMOV.TIPOITEM, 'N'),'I',NVL(PCMOV.QTCONT, 0),0) * NVL(PCMOV.VLFRETE, 0))) -
           (ROUND((NVL(PCMOV.QT, 0) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.VLIPI, 0)))),2)) - 
           (ROUND(NVL(PCMOV.QT, 0) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.ST, 0))),2))
 ELSE
           ROUND((((DECODE(PCMOV.CODOPER,'S',(NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'ST',
          (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)), 'SM',
          (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),0)) *
          (NVL(DECODE(PCNFSAID.CONDVENDA,7,(NVL(PUNITCONT, 0) - NVL(PCMOV.VLIPI, 0) - (nvl(pcmov.ST, 0) + NVL(PCMOVCOMPLE.VLSTTRANSFCD, 0))) + 
          NVL(PCMOV.VLFRETE, 0) + NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) +  DECODE(PCMOV.TIPOITEM,'C',
          (SELECT NVL((SUM(M.QTCONT * NVL(M.VLOUTROS,0)) / PCMOV.QT),0) VLOUTROS
               FROM PCMOV M
             WHERE M.NUMTRANSVENDA = PCMOV.NUMTRANSVENDA
               AND M.TIPOITEM = 'I'
               AND CODPRODPRINC = PCMOV.CODPROD),'I',NVL(PCMOV.VLOUTROS, 0),
           DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF, 'N'), 'N',NVL((PCMOV.VLOUTROS),0),'S', NVL((NVL(PCMOV.VLOUTROS,0) -
           NVL(PCMOV.VLREPASSE,0)),0))),(NVL(PCMOV.PUNIT, 0) - NVL(PCMOV.VLIPI, 0) - (nvl(pcmov.ST, 0) +  NVL(PCMOVCOMPLE.VLSTTRANSFCD, 0))) + 
           NVL(PCMOV.VLFRETE, 0) + NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) + DECODE(PCMOV.TIPOITEM,'C',
         (SELECT NVL((SUM(M.QTCONT * NVL(M.VLOUTROS,0)) / PCMOV.QT),0) VLOUTROS
            FROM PCMOV M
           WHERE M.NUMTRANSVENDA = PCMOV.NUMTRANSVENDA
             AND M.TIPOITEM = 'I'
             AND CODPRODPRINC = PCMOV.CODPROD),'I',
             NVL(PCMOV.VLOUTROS, 0),DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',NVL((PCMOV.VLOUTROS),0),'S',
             NVL((NVL(PCMOV.VLOUTROS,0) - NVL(PCMOV.VLREPASSE,0)),0)))),0)))),2)
         END AS VLVENDA,
         ROUND((NVL(PCPRODUT.PESOBRUTO, PCMOV.PESOBRUTO) * NVL(PCMOV.QT, 0)),2) AS TOTPESO,
         PCMOV.CODCLI QTCLIPOS
FROM PCNFSAID,
                   PCPRODUT,
                   PCMOV,
                   PCUSUARI,
                   PCPRACA,
                   PCPEDC,
                   PCMOVCOMPLE
WHERE PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
                   AND PCMOV.CODFILIAL = PCNFSAID.CODFILIAL
                   AND PCMOV.CODPROD = PCPRODUT.CODPROD
                   AND PCNFSAID.CODPRACA = PCPRACA.CODPRACA(+)
                   AND PCNFSAID.CODUSUR = PCUSUARI.CODUSUR
                   AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
                   AND PCMOV.CODOPER <> 'SR'
                   AND NVL(PCNFSAID.TIPOVENDA, 'X') NOT IN ('SR', 'DF')
                   AND PCMOV.CODOPER <> 'SO'
                   AND PCNFSAID.NUMPED = PCPEDC.NUMPED(+)
                   AND PCNFSAID.CODFISCAL NOT IN (522, 622, 722, 532, 632, 732)
                   AND PCNFSAID.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
                   AND (PCNFSAID.DTCANCEL IS NULL)
                   AND PCMOV.DTMOV BETWEEN TO_DATE('01/09/2022', 'DD/MM/YYYY') AND TO_DATE('30/09/2022', 'DD/MM/YYYY')
                   AND PCNFSAID.DTSAIDA BETWEEN TO_DATE('01/09/2022', 'DD/MM/YYYY') AND TO_DATE('30/09/2022', 'DD/MM/YYYY')
                   AND PCMOV.CODFILIAL IN ('1')
                   AND PCNFSAID.CODFILIAL IN ('1'))
GROUP BY CODPRACA, PRACA) VENDAS,
(SELECT CODPRACA,
                   PRACA,
                   SUM(NVL(QTDEVOLUCAO, 0)) QTDEVOLUCAO,
                   SUM(NVL(VLDEVOLUCAO, 0)) VLDEVOLUCAO,
                   SUM(NVL(TOTPESO, 0)) TOTPESO
FROM (SELECT 
             PCPRACA.CODPRACA,
             PCPRACA.PRACA,
             (NVL(PCMOV.QT, 0)) QT,
             (NVL(PCMOV.QT, 0)) QTDEVOLUCAO,
CASE
               WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM, 0) <> 0 THEN
                NVL(PCMOVCOMPLE.VLSUBTOTITEM, 0) -   (ROUND((NVL(PCMOV.QT, 0) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,
                DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.VLIPI, 0)))),2)) - (ROUND(NVL(PCMOV.QT, 0) *
                DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.ST, 0))),2))
ELSE
                (DECODE(PCNFSAID.CONDVENDA,5,0,DECODE(NVL(PCMOVCOMPLE.BONIFIC, 'N'),'N',NVL(PCMOV.QT, 0),0)) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,
                (DECODE(PCMOV.PUNIT,0,PCMOV.PUNITCONT,NULL,PCMOV.PUNITCONT,PCMOV.PUNIT) + NVL(PCMOV.VLFRETE, 0) +
                 NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) - (decode(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',
                (DECODE(NVL(PCMOV.VLOUTROS, 0),0,NVL(PCMOV.VLREPASSE, 0),0)),'S',(NVL(PCMOV.VLREPASSE, 0)))) + NVL(PCMOV.VLOUTROS, 0))))
END AS VLDEVOLUCAO,
            (NVL(PCPRODUT.PESOBRUTO, PCMOV.PESOBRUTO) * NVL(PCMOV.QT, 0)) AS TOTPESO                  
FROM PCNFENT,
                 PCESTCOM,
                 PCNFSAID,
                 PCMOV,
                 PCPRODUT,
                 PCCLIENT,
                 PCPRACA,
                 PCPEDC,
                 PCMOVCOMPLE
WHERE PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT
                 AND PCCLIENT.CODPRACA = PCPRACA.CODPRACA
                 AND PCESTCOM.NUMTRANSENT = PCMOV.NUMTRANSENT
                 AND PCNFSAID.NUMPED = PCPEDC.NUMPED(+)
                 AND PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA(+)
                 AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
                 AND PCESTCOM.NUMTRANSVENDA <> 0
                 AND PCMOV.CODPROD = PCPRODUT.CODPROD
                 AND PCNFENT.CODFORNEC = PCCLIENT.CODCLI
                 AND PCNFENT.TIPODESCARGA IN ('6', '7', 'T')
                 AND NVL(PCNFENT.CODFISCAL, 0) IN  (131, 132, 231, 232, 199, 299)
                 AND PCMOV.DTCANCEL IS NULL
                 AND PCMOV.CODOPER = 'ED'
                 AND NVL(PCNFENT.TIPOMOVGARANTIA, -1) = -1
                 AND NVL(PCNFENT.OBS, 'X') <> 'NF CANCELADA'
                 AND NVL(PCNFSAID.CONDVENDA, 0) NOT IN (4, 8, 10, 13, 20, 98, 99)                   
                 AND PCMOV.CODFILIAL IN ('1')
                 AND PCNFENT.CODFILIAL IN ('1')
                 AND PCNFENT.DTENT BETWEEN TO_DATE('01/09/2022', 'DD/MM/YYYY') AND TO_DATE('30/09/2022', 'DD/MM/YYYY')
                 AND PCMOV.DTMOV BETWEEN TO_DATE('01/09/2022', 'DD/MM/YYYY') AND TO_DATE('30/09/2022', 'DD/MM/YYYY'))
GROUP BY CODPRACA, PRACA) DEVOLUCAO,PCPRACA
WHERE PCPRACA.CODPRACA = VENDAS.CODPRACA(+)
       AND PCPRACA.CODPRACA = DEVOLUCAO.CODPRACA(+)
       AND ((NVL(VENDAS.QTVENDA, 0) <> 0) or  (NVL(DEVOLUCAO.QTDEVOLUCAO, 0) <> 0) or(NVL(DEVOLUCAO.VLDEVOLUCAO, 0) <> 0) OR
       (NVL(VENDAS.TOTPESO, 0) <> 0) OR (NVL(VENDAS.VLVENDA, 0) <> 0)  OR (NVL(VENDAS.QTCLIPOS, 0) <> 0))
GROUP BY VENDAS.CODPRACA,
                       VENDAS.PRACA,
                       DEVOLUCAO.CODPRACA,
                       DEVOLUCAO.PRACA
ORDER BY VLVENDA DESC
