-- CMV Devolucao 
SELECT SUM(TOTAL.VLCMVDEVOL) VLCMVDEVOL
 FROM (
SELECT 
SUM((DEVOL.VLCMVDEVOLBONIF + DEVOL.VLCMVDEVOL)) VLCMVDEVOL,
 NULL VLDEVCMVAVULSAI
   FROM VIEW_DEVOL_RESUMO_FATURAMENTO DEVOL
  WHERE 1 = 1
  AND DEVOL.CODFILIAL IN ('1')  
  AND DEVOL.DTENT BETWEEN '01-09-2022' and '17-09-2022'
 AND DEVOL.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
UNION ALL SELECT 
 NULL VLCMVDEVOL,
SUM(AVULSA.VLDEVCMVAVULSAI) VLDEVCMVAVULSAI
   FROM VIEW_DEVOL_RESUMO_FATURAVULSA AVULSA
  WHERE 1 = 1
  AND AVULSA.CODFILIAL IN ('1')  
  AND AVULSA.DTENT  BETWEEN '01-09-2022' and '17-09-2022'
) TOTAL 
