SELECT PCPLPAG.CODPLPAG,
       PCPLPAG.DESCRICAO DESCRIÇÃO, 
       PCPLPAG.NUMDIAS, 
       SUM(NVL(VENDAS.QTVENDA,0) - NVL(DEVOLUCAO.QTDEVOLUCAO,0)) QTVENDA,
       SUM(NVL(VENDAS.VLVENDA,0) - NVL(DEVOLUCAO.VLDEVOLUCAO,0)) VLVENDA,
       SUM(NVL(VENDAS.VLBONIFIC,0)) - SUM(NVL(DEVOLUCAO.VLBONIFIC,0)) VLBONIFIC,
       SUM(NVL(DEVOLUCAO.VLDEVOLUCAO,0)) VLDEVOLUCAO,
       SUM(NVL(VENDAS.TOTPESO,0) - NVL(DEVOLUCAO.TOTPESO,0) ) TOTPESO
FROM  (SELECT CODPLPAG,
              DESCRICAOPCPLPAG, NUMDIAS, 
              SUM(NVL(QTVENDA,0)) QTVENDA,
              SUM(NVL(VLVENDA,0) + NVL(VALORST,0) + NVL(VALORIPI,0)) VLVENDA,
              SUM(NVL(VLBONIFIC,0)) VLBONIFIC,
              SUM(NVL(TOTPESO,0)) TOTPESO
FROM (  SELECT 
       PCNFSAID.CODPLPAG,
       PCPLPAG.DESCRICAO DESCRICAOPCPLPAG,
       PCPLPAG.NUMDIAS, 
    ---   ROUND((DECODE(PCMOV.CODOPER,'SB',PCMOV.QTCONT,0)) * NVL(PCMOV.VLREPASSE, 0), 2) VLREPASSEBNF,              
       ROUND((NVL(PCMOV.QT, 0) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.VLIPI,0)))),2) VALORIPI,
       ROUND(NVL(PCMOV.QT, 0) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,DECODE(PCMOV.CODOPER,'SB',0,(nvl(pcmov.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0)))),2) VALORST,
     ((DECODE(PCMOV.CODOPER,'S', 
     (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'SM',
     (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'ST', 
     (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'SB', 
     (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),0))) QTVENDA, 
     ((DECODE(PCMOV.CODOPER,'S',
     (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'ST',
     (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'SM',
     (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'SB',
     (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),0)) * 
     (NVL(PCMOV.CUSTOFIN, 0))) VLCUSTOFIN,  
CASE WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM,0) <> 0 THEN  
       DECODE(NVL(PCMOV.TIPOITEM,'N'),'I',0,NVL(PCMOVCOMPLE.VLSUBTOTITEM,0) + (DECODE(NVL(PCMOV.TIPOITEM,'N'),'I', NVL(PCMOV.QTCONT, 0), 0) * NVL(PCMOV.VLFRETE, 0))) - 
       (ROUND((NVL(PCMOV.QT, 0) *  DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,
       DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.VLIPI,0)))),2)) -  
       (ROUND(NVL(PCMOV.QT, 0) * DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0,
       DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.ST,0))),2)) 
ELSE                                                
       ROUND((((DECODE(PCMOV.CODOPER,'S',                                                   
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'ST',                                                  
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'SM',                                                  
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),0)) *                                                    
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,                                                   
       (NVL(PUNITCONT, 0) - NVL(PCMOV.VLIPI, 0) -           
       (nvl(pcmov.ST,0)+NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))) + NVL(PCMOV.VLFRETE, 0) +
     NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) + DECODE(PCMOV.TIPOITEM, 'C',                                        
    (SELECT NVL((SUM(M.QTCONT * NVL(M.VLOUTROS, 0)) / PCMOV.QT), 0) VLOUTROS                
     FROM PCMOV M                               
    WHERE M.NUMTRANSVENDA = PCMOV.NUMTRANSVENDA                   
      AND M.TIPOITEM = 'I'                    
      AND CODPRODPRINC = PCMOV.CODPROD),'I', 
      NVL(PCMOV.VLOUTROS, 0),DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',
      NVL((PCMOV.VLOUTROS), 0),'S',NVL((NVL(PCMOV.VLOUTROS,0)-NVL(PCMOV.VLREPASSE,0)), 0))),
      (NVL(PCMOV.PUNIT, 0) - NVL(PCMOV.VLIPI, 0) - (nvl(pcmov.ST,0)+
      NVL(PCMOVCOMPLE.VLSTTRANSFCD,0))) + NVL(PCMOV.VLFRETE, 0) +          
      NVL(PCMOV.VLOUTRASDESP, 0) +  NVL(PCMOV.VLFRETE_RATEIO, 0) +                       
      DECODE(PCMOV.TIPOITEM, 'C',                                        
        (SELECT NVL((SUM(M.QTCONT *  NVL(M.VLOUTROS, 0)) / PCMOV.QT), 0) VLOUTROS                
           FROM PCMOV M                               
          WHERE M.NUMTRANSVENDA =    PCMOV.NUMTRANSVENDA                   
            AND M.TIPOITEM = 'I'                    
            AND CODPRODPRINC = PCMOV.CODPROD),'I', NVL(PCMOV.VLOUTROS, 0), 
 DECODE(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N',NVL((PCMOV.VLOUTROS), 0),'S',NVL((NVL(PCMOV.VLOUTROS,0)-NVL(PCMOV.VLREPASSE,0)), 0)))),0)))),2) END AS VLVENDA,                                                                                          
      ROUND((NVL(PCMOV.QT, 0) * (DECODE(PCNFSAID.CONDVENDA,5,
               DECODE(PCMOV.PBONIFIC, NULL, PCMOV.PTABELA, PCMOV.PBONIFIC),6,
               DECODE(PCMOV.PBONIFIC, NULL, PCMOV.PTABELA, PCMOV.PBONIFIC),11,
               DECODE(PCMOV.PBONIFIC, NULL, PCMOV.PTABELA, PCMOV.PBONIFIC),1,
               NVL(PCMOV.PBONIFIC,0),14,
               NVL(PCMOV.PBONIFIC,0),12,
               DECODE(PCMOV.PBONIFIC, NULL, PCMOV.PTABELA, PCMOV.PBONIFIC),0))),2) VLBONIFIC,
               ((DECODE(PCMOV.CODOPER,'S',
               (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'ST',
               (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),'SM',
               (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),0))) QTVENDIDA,
       ROUND( (NVL(PCPRODUT.PESOBRUTO,PCMOV.PESOBRUTO) * NVL(PCMOV.QT, 0)),2) AS TOTPESO,
       ROUND(PCMOV.QT * (PCMOV.PTABELA + NVL (pcmov.vlfrete, 0) + NVL (pcmov.vloutrasdesp, 0) + NVL (pcmov.vlfrete_rateio, 0) + NVL (pcmov.vloutros, 0)),2) VLTABELA
  FROM 
       PCNFSAID,
       PCPRODUT,
       PCMOV,
       PCUSUARI,
       PCPLPAG,
    --   PCMARCA,
       PCMOVCOMPLE
 WHERE PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
   AND PCMOV.CODFILIAL = PCNFSAID.CODFILIAL 
   AND PCMOV.DTMOV BETWEEN TO_DATE('01/10/2022','DD/MM/YYYY') AND TO_DATE('31/10/2022', 'DD/MM/YYYY') 
   AND PCMOV.CODPROD = PCPRODUT.CODPROD
   AND  PCNFSAID.CODUSUR   = PCUSUARI.CODUSUR 
   AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
   AND PCMOV.CODOPER <> 'SR' 
   AND NVL(PCNFSAID.TIPOVENDA,'X') NOT IN ('SR', 'DF')
   AND PCMOV.CODOPER <> 'SO' 
   AND PCNFSAID.CODPLPAG = PCPLPAG.CODPLPAG
   AND PCNFSAID.CODFISCAL NOT IN (522, 622, 722, 532, 632, 732)
   AND PCNFSAID.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
   AND (PCNFSAID.DTCANCEL IS NULL)
   AND PCNFSAID.DTSAIDA BETWEEN TO_DATE('01/10/2022', 'DD/MM/YYYY') AND TO_DATE('31/10/2022', 'DD/MM/YYYY') 
   AND PCMOV.CODFILIAL IN('1')
   AND PCNFSAID.CODFILIAL IN('1'))
GROUP BY CODPLPAG, DESCRICAOPCPLPAG, NUMDIAS) VENDAS, 
(SELECT CODPLPAG, NUMDIAS,
               SUM(NVL(QTDEVOLUCAO,0)) QTDEVOLUCAO,
               SUM(NVL(VLDEVOLUCAO,0)) VLDEVOLUCAO,
               SUM(NVL(TOTPESO,0)) TOTPESO,
               SUM(NVL(VLCUSTOFIN,0)) VLCUSTOFIN,
               SUM(NVL(VLBONIFIC,0)) VLBONIFIC
FROM  (SELECT 
       NVL(PCNFSAID.CODPLPAG,PCCLIENT.CODPLPAG) CODPLPAG, 
       PCPLPAG.DESCRICAO DESCRICAOPCPLPAG,
       NVL(PCPLPAG.NUMDIAS,0) NUMDIAS,
       ROUND(DECODE(PCNFSAID.CONDVENDA,5,0,DECODE(NVL(PCMOVCOMPLE.BONIFIC, 'N'),'N',NVL(PCMOV.QT, 0),0)) * NVL(PCMOV.VLREPASSE, 0),2) VLREPASSE,                                
       ROUND(DECODE(PCNFSAID.CONDVENDA,5,NVL(PCMOV.QT, 0),DECODE(NVL(PCMOVCOMPLE.BONIFIC, 'N'),'N',0,NVL(PCMOV.QT, 0),0)) * NVL(PCMOV.VLREPASSE, 0),2) VLREPASSEBNF,                             
 (NVL(PCMOV.QT,0)) QT,        
     (NVL(PCMOV.QT,0)) QTDEVOLUCAO,
CASE WHEN NVL(PCMOVCOMPLE.VLSUBTOTITEM,0) <> 0 THEN  
      NVL(PCMOVCOMPLE.VLSUBTOTITEM,0) - (ROUND((NVL(PCMOV.QT, 0) * 
      DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,12,0, 
      DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.VLIPI,0)))),2)) - (ROUND(NVL(PCMOV.QT, 0) * 
      DECODE(PCNFSAID.CONDVENDA, 5,0,6,0,11,0,12,0,
      DECODE(PCMOV.CODOPER,'SB',0,nvl(pcmov.ST,0))),2)) 
ELSE                                                
  (DECODE(PCNFSAID.CONDVENDA, 5, 0, DECODE(NVL(PCMOVCOMPLE.BONIFIC, 'N'), 'N', NVL(PCMOV.QT, 0), 0)) * 
  DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,                                                                   
  (DECODE(PCMOV.PUNIT,0,PCMOV.PUNITCONT,NULL,PCMOV.PUNITCONT,PCMOV.PUNIT) + NVL(PCMOV.VLFRETE, 0) +                        
   NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) - (decode(NVL(PCNFSAID.SOMAREPASSEOUTRASDESPNF,'N'),'N', 
  (DECODE(NVL(PCMOV.VLOUTROS,0),0,NVL(PCMOV.VLREPASSE,0),0)),'S',(NVL(PCMOV.VLREPASSE,0)))) + NVL(PCMOV.VLOUTROS, 0)))) END AS VLDEVOLUCAO,                          
  (DECODE(PCNFSAID.CONDVENDA, 5, 0, DECODE(NVL(PCMOVCOMPLE.BONIFIC, 'N'), 'N', NVL(PCMOV.QT, 0), 0)) * 
  DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,(nvl(PCMOV.ST,0) + NVL(PCMOVCOMPLE.VLSTTRANSFCD,0)) )) VALORST,                                                                                                       
  (DECODE(PCNFSAID.CONDVENDA,5,0,DECODE(NVL(PCMOVCOMPLE.BONIFIC, 'N'), 'N', NVL(PCMOV.QT, 0), 0)) * 
  DECODE(PCNFSAID.CONDVENDA,5,0,6,0,11,0,nvl(PCMOV.VLIPI,0) )) VALORIPI,                                          
  (NVL(PCMOV.QT, 0) * (DECODE(PCNFSAID.CONDVENDA,5,                                                                    
   NVL(PCMOV.PUNITCONT, 0),0) + NVL(PCMOV.VLOUTROS, 0) + NVL(PCMOV.VLFRETE, 0))) VLDEVOLUCAOBNF,                          
  (NVL(PCMOV.QT, 0) * (DECODE(PCNFSAID.CONDVENDA,5,                                                                   
   NVL(PCMOV.PUNITCONT, 0),6,                                                                   
   NVL(PCMOV.PUNITCONT, 0),11,                                                                  
   NVL(PCMOV.PUNITCONT, 0),12,                                                                  
   NVL(PCMOV.PUNITCONT, 0),0) + DECODE(PCNFSAID.CONDVENDA,5,                                                     
   NVL(PCMOV.VLOUTROS, 0),6,                                                     
   NVL(PCMOV.VLOUTROS, 0),11,                                                    
   NVL(PCMOV.VLOUTROS, 0),12,                                                    
   NVL(PCMOV.VLOUTROS, 0)) +                              
  DECODE(PCNFSAID.CONDVENDA,5,                                                                   
   NVL(PCMOV.VLFRETE, 0),6,                                                                   
   NVL(PCMOV.VLFRETE, 0),11,                                                                  
   NVL(PCMOV.VLFRETE, 0),12,                                                                  
   NVL(PCMOV.VLFRETE, 0)))) VLDEVOLUCAOBONI,                            
  (NVL(PCMOV.QT, 0) * NVL(PCMOV.CUSTOFIN, 0)) VLCMVDEVOL,                       
  (NVL(PCMOV.QT, 0) * (NVL(PCMOV.CUSTOFIN, 0))) VLCUSTOFIN,                                                                                    
  (DECODE(PCMOV.PBASERCA,NULL,                                                                 
   NVL(PCMOV.PBASERCA, NVL(PCMOV.PTABELA, 0)),                           
   NVL(PCMOV.PTABELA, 0)) * NVL(PCMOV.QT, 0)) DEVOLTAB,                  
  (NVL(PCPRODUT.PESOBRUTO,PCMOV.PESOBRUTO) * NVL(PCMOV.QT, 0)) AS TOTPESO,     
  ROUND((NVL(PCMOV.QT, 0) *DECODE(PCNFSAID.CONDVENDA, 5,                                                              
  DECODE(PCMOV.PBONIFIC,NULL,PCMOV.PTABELA,PCMOV.PBONIFIC) /*+ NVL(PCMOV.VLFRETE, 0)*/ +                
  NVL(PCMOV.VLOUTRASDESP, 0) +                                    
  NVL(PCMOV.VLFRETE_RATEIO, 0) + NVL(PCMOV.VLOUTROS, 0),6,                                                             
  DECODE(PCMOV.PBONIFIC,NULL,PCMOV.PTABELA,PCMOV.PBONIFIC),1,                                                              
  NVL(PCMOV.PBONIFIC,0),14,                                                            
  NVL(PCMOV.PBONIFIC,0),11,                                                             
  DECODE(PCMOV.PBONIFIC,NULL,PCMOV.PTABELA,PCMOV.PBONIFIC),12,                                                             
  DECODE(PCMOV.PBONIFIC,NULL,PCMOV.PTABELA,PCMOV.PBONIFIC),0)),2) VLBONIFIC,                                                        
CASE WHEN (SELECT SUM (NVL(PCMOV.QT, 0) * (NVL(PCMOV.PUNIT, 0) + NVL(PCMOV.VLOUTROS, 0)) )
     FROM PCMOV M, PCESTCOM E, PCNFENT  F
         WHERE E.NUMTRANSENT = F.NUMTRANSENT AND M.NUMTRANSENT = F.NUMTRANSENT
         AND M.CODOPER = 'ED' AND M.DTCANCEL IS NULL
         AND PCNFSAID.NUMTRANSVENDA = E.NUMTRANSVENDA )  >= NVL(PCNFSAID.VLTOTAL,0) THEN
            PCFORNEC.CODFORNEC 
            ELSE
            0 END DEVOLVIDO, 
      (SELECT PCCLIENT.CODPLPAG || ' - ' || PCPLPAG.DESCRICAO  FROM PCPLPAG WHERE PCCLIENT.CODPLPAG = PCPLPAG.CODPLPAG) DESCRICAOPLANOCLI
  FROM 
      PCNFENT, 
      PCESTCOM, 
      PCEMPR,
      PCNFSAID, 
      PCMOV, 
      PCPRODUT, 
      PCCLIENT,
      PCFORNEC,
      PCDEPTO,
      PCUSUARI, 
      PCPLPAG, 
      PCPEDC,
      PCCIDADE, 
      PCMARCA,
      PCGERENTE, 
      PCMOVCOMPLE 
 WHERE PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT
   AND PCESTCOM.NUMTRANSENT = PCMOV.NUMTRANSENT
   AND PCFORNEC.CODFORNEC = PCPRODUT.CODFORNEC
   AND PCNFSAID.NUMPED  = PCPEDC.NUMPED(+)
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)     
   AND PCNFENT.CODUSURDEVOL = PCUSUARI.CODUSUR(+)
   AND PCNFENT.CODFUNCLANC  = PCEMPR.MATRICULA(+)
   AND PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA(+)
   AND PCCLIENT.CODCIDADE = PCCIDADE.CODCIDADE(+)
   AND NVL(PCNFSAID.CODPLPAG,PCCLIENT.CODPLPAG) = PCPLPAG.CODPLPAG
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+)
   AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
   AND PCNFSAID.CODGERENTE = PCGERENTE.CODGERENTE(+)
   AND PCESTCOM.NUMTRANSVENDA <> 0
   AND PCMOV.CODPROD = PCPRODUT.CODPROD
   AND PCNFENT.CODFORNEC = PCCLIENT.CODCLI 
   AND PCNFENT.TIPODESCARGA IN ('6', '7', 'T')
   AND NVL(PCNFENT.CODFISCAL,0) IN (131, 132, 231, 232, 199, 299)
   AND PCMOV.DTCANCEL IS NULL
   AND PCMOV.CODOPER = 'ED' 
   AND NVL(PCNFENT.TIPOMOVGARANTIA, -1) = -1
   AND NVL(PCNFENT.OBS, 'X') <> 'NF CANCELADA'
   AND NVL(PCNFSAID.CONDVENDA, 0) NOT IN (4, 8, 10, 13, 20, 98, 99)
   AND PCMOV.CODFILIAL IN('1')
   AND PCNFENT.CODFILIAL IN('1')
   AND PCNFENT.DTENT BETWEEN TO_DATE('01/10/2022','DD/MM/YYYY') AND TO_DATE('31/10/2022', 'DD/MM/YYYY') 
   AND PCMOV.DTMOV BETWEEN TO_DATE('01/10/2022','DD/MM/YYYY') AND TO_DATE('31/10/2022', 'DD/MM/YYYY') )
GROUP BY CODPLPAG, NUMDIAS) DEVOLUCAO, PCPLPAG
WHERE PCPLPAG.CODPLPAG = VENDAS.CODPLPAG(+)
  AND PCPLPAG.CODPLPAG = DEVOLUCAO.CODPLPAG(+)
  AND ((NVL(VENDAS.QTVENDA,0) <> 0)  or  (NVL(DEVOLUCAO.QTDEVOLUCAO,0) <> 0)  or  ( NVL(DEVOLUCAO.VLDEVOLUCAO,0) <> 0) 
 OR (NVL(VENDAS.TOTPESO,0) <> 0)  OR (NVL(VENDAS.VLVENDA,0) <> 0)  OR (NVL(VENDAS.VLBONIFIC,0) <> 0)   OR (NVL(VENDAS.CODPLPAG,0) <> 0) ) 
GROUP BY PCPLPAG.CODPLPAG,PCPLPAG.DESCRICAO, PCPLPAG.NUMDIAS 
ORDER BY VLVENDA DESC 
