SELECT
 PCCORTEFV.codprod,
 PCPRODUT.DESCRICAO,
 PCCORTEFV.CODAUXILIAR,
 SUM(PCCORTEFV.Qtcorte)
  FROM PCCORTEFV, PCCLIENT, PCUSUARI, PCPRODUT
 WHERE PCCORTEFV.CODCLI = PCCLIENT.CODCLI
   AND PCCORTEFV.CODUSUR = PCUSUARI.CODUSUR
   AND PCCORTEFV.CODPROD = PCPRODUT.CODPROD
   and PCCORTEFV.CODUSUR = 52 
   AND TRUNC(PCCORTEFV.DTCORTE) BETWEEN '01-11-2021' AND '30-11-2021'
 GROUP BY PCCORTEFV.codprod, PCPRODUT.DESCRICAO,  PCCORTEFV.CODAUXILIAR
 ORDER BY PCCORTEFV.codprod

