SELECT PCEST.CODPROD, PCEST.custoultent,       (PKG_ESTOQUE.ESTOQUE_DISPONIVEL(PCEST.CODPROD, PCEST.CODFILIAL, 'V')) QTDISP,         PCEST.DTULTENT
  FROM PCEST
 WHERE PCEST.CODFILIAL = 1
   AND CODPROD in (16,50)




