SELECT DISTINCT
        
        L.DTPAGTO AS DATA_PAGAMENTO, 
        B.CODFORNEC AS CODIGO_FORNECEDOR,
        L.TIPOPARCEIRO,
        B.FORNECEDOR, 
        L.HISTORICO, 
        L.NUMNOTA AS NUMERO_NOTA, 
        L.DUPLIC AS PARCELA, 
        L.VALOR AS VLLIQUIDO,
        L.VPAGO AS VALOR_PAGO, 
        L.CODFILIAL AS CODIGO_FILIAL, 
        L.DESCONTOFIN AS DESCONTO_FINANCEIRO, 
        L.TXPERM AS JUROS, 
        L.NUMBANCO AS BANCO

        
        FROM PCLANC L, PCFORNEC B
        
        WHERE L.CODFORNEC = B.CODFORNEC
        
        AND L.CODFILIAL = 1
        AND L.TIPOPARCEIRO = 'F'                   
        AND L.DTPAGTO  BETWEEN '01-09-2022' AND '30-09-2022'
        
        
UNION ALL


SELECT DISTINCT
        
        L.DTPAGTO AS DATA_PAGAMENTO, 
        C.MATRICULA AS CODIGO_FORNECEDOR,
        L.TIPOPARCEIRO,
        C.NOME, 
        L.HISTORICO, 
        L.NUMNOTA AS NUMERO_NOTA, 
        L.DUPLIC AS PARCELA, 
        L.VALOR AS VLLIQUIDO,
        L.VPAGO AS VALOR_PAGO, 
        L.CODFILIAL AS CODIGO_FILIAL, 
        L.DESCONTOFIN AS DESCONTO_FINANCEIRO, 
        L.TXPERM AS JUROS, 
        L.NUMBANCO AS BANCO

        
        FROM PCLANC L, PCEMPR C
        
        WHERE L.CODFORNEC = C.MATRICULA
        
        AND L.CODFILIAL = 1
        AND L.TIPOPARCEIRO = 'M'                       
        AND L.DTPAGTO  BETWEEN '01-09-2022' AND '30-09-2022'

UNION ALL


SELECT DISTINCT
        
        L.DTPAGTO AS DATA_PAGAMENTO, 
        C.MATRICULA AS CODIGO_FORNECEDOR,
        L.TIPOPARCEIRO,
        C.NOME, 
        L.HISTORICO, 
        L.NUMNOTA AS NUMERO_NOTA, 
        L.DUPLIC AS PARCELA, 
        L.VALOR AS VLLIQUIDO,
        L.VPAGO AS VALOR_PAGO, 
        L.CODFILIAL AS CODIGO_FILIAL, 
        L.DESCONTOFIN AS DESCONTO_FINANCEIRO, 
        L.TXPERM AS JUROS, 
        L.NUMBANCO AS BANCO

        
        FROM PCLANC L, PCEMPR C
        
        WHERE L.CODFORNEC = C.MATRICULA
        
        AND L.CODFILIAL = 1
        AND L.TIPOPARCEIRO = 'L'                       
        AND L.DTPAGTO  BETWEEN '01-09-2022' AND '30-09-2022'
        
UNION ALL


SELECT DISTINCT
        
        L.DTPAGTO AS DATA_PAGAMENTO, 
        C.CODUSUR AS CODIGO_FORNECEDOR,
        L.TIPOPARCEIRO,
        C.NOME, 
        L.HISTORICO, 
        L.NUMNOTA AS NUMERO_NOTA, 
        L.DUPLIC AS PARCELA, 
        L.VALOR AS VLLIQUIDO,
        L.VPAGO AS VALOR_PAGO, 
        L.CODFILIAL AS CODIGO_FILIAL, 
        L.DESCONTOFIN AS DESCONTO_FINANCEIRO, 
        L.TXPERM AS JUROS, 
        L.NUMBANCO AS BANCO

        
        FROM PCLANC L, PCUSUARI C
        
        WHERE L.CODFORNEC = C.CODUSUR
        
        AND L.CODFILIAL = 1
        AND L.TIPOPARCEIRO = 'R'                       
        AND L.DTPAGTO  BETWEEN '01-09-2022' AND '30-09-2022'

UNION ALL




SELECT DISTINCT
        
        L.DTPAGTO AS DATA_PAGAMENTO, 
        L.CODFORNEC AS CODIGO_FORNECEDOR,
        L.TIPOPARCEIRO,
        L.FORNECEDOR, 
        L.HISTORICO, 
        L.NUMNOTA AS NUMERO_NOTA, 
        L.DUPLIC AS PARCELA, 
        L.VALOR AS VLLIQUIDO,
        L.VPAGO AS VALOR_PAGO, 
        L.CODFILIAL AS CODIGO_FILIAL, 
        L.DESCONTOFIN AS DESCONTO_FINANCEIRO, 
        L.TXPERM AS JUROS, 
        L.NUMBANCO AS BANCO

        
        FROM PCLANC L
        
        WHERE L.CODFILIAL = 1
        
        AND L.TIPOPARCEIRO = 'O'                       
        AND L.DTPAGTO BETWEEN '01-09-2022' AND '30-09-2022'
