SELECT  
    (SELECT ROUND( NVL(SUM(ESTOQUE_WMS.QT) ,0),2) FROM ESTOQUE_WMS where produto_erp = PCPRODUT.CODPROD ) AS ESTOQUE_KAIZEN,
    ROUND ((PCEST.QTESTGER),2) AS ESTOQUE_WINTHOR,
    (SELECT ROUND( NVL(SUM(ESTOQUE_WMS.QT) ,0),2) FROM ESTOQUE_WMS where produto_erp = PCPRODUT.CODPROD ) - ROUND ((PCEST.QTESTGER),2) AS DIFERENÇA_ESTOQUE,
    PCINVENTROT.NUMINVENT,
    PCINVENTROT. DATA AS DATA_INVENTARIO,  
    PCINVENTROT.CODPROD, 
    
    CASE PCPRODUT.CODAUXILIAR 
      WHEN 0 THEN PCPRODUT.CODAUXILIAR2  
      WHEN NULL THEN PCPRODUT.CODAUXILIAR2
      ELSE PCPRODUT.CODAUXILIAR END,
      
    PCPRODUT.CODAUXILIAR,
    PCPRODUT.DESCRICAO,  
    PCPRODUT.CODFAB,
    PCINVENTROT.QT1,
    PCINVENTROT.QTESTGER, 
    ROUND((PCEST.QTESTANT),2) AS ESTOQUE_ANTERIORWINTHOR,
    PCINVENTROT.DATACONT1, 
    PCINVENTROT.QTUTILIZAATUALIZACAO,
    PCFORNEC.CODFORNEC,
    PCFORNEC.FORNECEDOR,
    PCDEPTO.DESCRICAO AS DEPARTAMENTO,
    ROUND((PCEST.QTULTENT),2), 
    'R$ ' || ROUND((PCEST.CUSTOULTENT),2),
    'R$ ' || ROUND((PCEST.QTULTENT * PCEST.CUSTOULTENT),2 )AS VALOR_ULTIMAENTRADA
     FROM PCINVENTROT , PCPRODUT, PCEST, PCFORNEC, PCDEPTO
    WHERE PCPRODUT.CODPROD = PCINVENTROT.CODPROD  
    AND PCPRODUT.CODPROD = PCEST.CODPROD 
    AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
    AND PCPRODUT.CODFORNEC  = PCFORNEC.CODFORNEC
    AND PCINVENTROT.CODPROD = PCEST.CODPROD
    AND PCINVENTROT.CODFILIAL = PCEST.CODFILIAL
    AND NUMINVENT =    160
   AND PCPRODUT.CODPROD =  11975


/*Boa tarde, preciso de um relatório que filtrado pelo número de inventário, ele puxe o código de barras, referencia, 
código do produto, descrição do produto, departamento, código do fornecedor, fornecedor, 
estoque anterior ao inventário WMS, estoque anterior ao inventário WINTHOR, 
estoque apurado na contagem, custo da última entrada, valor da última entrada, 
sobra/falta e valor de diferença .*/
