
SELECT EXTRACT(DAY FROM P.DATA) AS DIA,
       CASE EXTRACT(MONTH FROM P.DATA)
         WHEN 1 THEN 'JANEIRO'
         WHEN 2 THEN 'FEVEREIRO'
         WHEN 3 THEN 'MARÇO'
         WHEN 4 THEN 'ABRIL'
         WHEN 5 THEN 'MAIO'
         WHEN 6 THEN 'JUNHO'
         WHEN 7 THEN 'JULHO'
         WHEN 8 THEN 'AGOSTO'
         WHEN 9 THEN 'SETEMBRO'
         WHEN 10 THEN 'OUTUBRO'
         WHEN 11 THEN 'NOVEMBRO'
         WHEN 12 THEN 'DEZEMBRO'
           ELSE 'MES INVALIDO'
         END AS MÊS,
       U.CODUSUR AS RCA,
      SUM( P.VLTOTAL) AS VENDAS, 
       U.NOME AS NOME

FROM PCPEDC P, PCUSUARI U, PCSUPERV S
WHERE  P.CODUSUR = U.CODUSUR (+)
      AND P.CODSUPERVISOR = S.CODSUPERVISOR (+)
      AND U.BLOQUEIO = 'N'
      AND (SELECT TO_CHAR(P.DATA,'D') FROM DUAL) = 6 
      AND P.DATA >= '01/01/2022'

GROUP BY  U.CODUSUR, U.NOME, P.DATA, S.NOME
ORDER BY EXTRACT(MONTH FROM P.DATA), DIA,  RCA;
