SELECT PCNFENT.NUMNOTA
     -- ,PCNFENT.NUMTRANSENT AS NUM_TRANSACAO
      ,PCNFENT.VLTOTAL
    -- ,PCNFENT.CODFORNEC
   --   ,PCNFENT.SITUACAONFE
      ,PCNFENT.DTENT AS DTEMISSAO
    -- ,NVL(PCNFENT.TIPOEMISSAO,'1') AS TIPOEMISSAO
   --  ,PCMENSAGEMNFE.DESCRICAO
      ,(PCNFENT.HORALANC || ':' || PCNFENT.MINUTOLANC) HORA
    --  ,PCFILIAL.CODIGO AS CODIGO_FILIAL
      
           /* ,  NVL((SELECT MIN(PCCFO.CODFISCAL) CODFISCAL
                   FROM PCCFO
                       ,PCMOV
                  WHERE PCMOV.CODFISCAL = PCCFO.CODFISCAL
                    AND PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT),
                 (SELECT MIN(PCCFO.CODFISCAL) CODFISCAL
                    FROM PCCFO
                   WHERE PCCFO.CODFISCAL =
                         (SELECT NVL(MAX(PCNFBASE.CODFISCAL),
                                     0)
                            FROM PCNFBASE
                          WHERE PCNFBASE.NUMTRANSENT = PCNFENT.NUMTRANSENT))) AS CODFISCAL
            ,NVL((SELECT MIN(PCCFO.DESCCFO) DESCCFO
                   FROM PCCFO
                       ,PCMOV
                  WHERE PCMOV.CODFISCAL = PCCFO.CODFISCAL
                    AND PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT),
                (SELECT MIN(PCCFO.DESCCFO) DESCCFO
                    FROM PCCFO
                   WHERE PCCFO.CODFISCAL =
                         (SELECT NVL(MAX(PCNFBASE.CODFISCAL),
                                     0)
                            FROM PCNFBASE
                           WHERE PCNFBASE.NUMTRANSENT = PCNFENT.NUMTRANSENT))) AS DESCRICAO_CFOP
            ,DECODE(NVL(PCNFENT.AMBIENTENFE,
                    'X'),
            'H',
             2,
            'P',
             1,
              3) AS AMBIENTE 
            ,NVL(PCNFENT.TIPOEMISSAO,'0') AS TIPOEMISSAO */
            ,'E' AS TIPOMOV 
            ,PCNFENT.CHAVENFE 
FROM   PCNFENT,PCFILIAL
      ,PCMENSAGEMNFE
WHERE  
       PCNFENT.SITUACAONFE NOT IN
       (0,100, 1001, 100, 101, 102, 103, 104, 105, 106, 107, 124, 150, 110, 205, 301, 302, 303, 305)
AND    PCNFENT.ESPECIE IN( 'NE','NF')
AND    NVL(PCNFENT.OBS,' ') <> 'NF CANCELADA'
AND    NVL(PCNFENT.CODFILIALNF,PCNFENT.CODFILIAL) = PCFILIAL.CODIGO
AND    NVL(PCFILIAL.UTILIZANFE,'N') = 'S'
AND    PCNFENT.DTEMISSAO >= TRUNC(SYSDATE)-1825
AND    PCNFENT.SITUACAONFE = PCMENSAGEMNFE.CODMENSAGEM(+)
ORDER  BY PCNFENT.NUMNOTA 