SELECT PCPRODUT.CODPROD,
       PCPRODUT.DESCRICAO,       
       PCEST.QTESTGER as ESTOQUE_GERENCIAL,
       F.QTESTGER     AS ESTOQUE_FISCAL,        
       NVL(PCEST.CUSTOULTENT, 0) CUSTOULTENT,
       PCTABPR.PVENDA
  FROM PCPRODUT,
       PCEST,       
       PCEST@BIGATACFILIAL F,     
       PCFILIAL,
       PCPRODFILIAL,
       PCTABPR
 WHERE PCEST.CODPROD = PCPRODUT.CODPROD(+)
   AND PCPRODUT.CODPROD = PCPRODFILIAL.CODPROD(+)
   AND F.CODFILIAL IN ('1')
   AND PCEST.CODFILIAL = PCPRODFILIAL.CODFILIAL      
   AND PCEST.CODFILIAL = PCFILIAL.CODIGO
   AND PCTABPR.NUMREGIAO = 1
   AND PCPRODUT.CODPROD = PCTABPR.CODPROD
   AND F.CODPROD = PCPRODUT.CODPROD      
   AND ((PCPRODUT.CODFILIAL = F.CODFILIAL) OR (PCPRODUT.CODFILIAL = '99') OR
       (PCPRODUT.CODFILIAL IS NULL))      
--   AND NVL(F.QTESTGER, 0) > 0      
   AND ((PCPRODUT.CODFILIAL = PCEST.CODFILIAL) OR
       (PCPRODUT.CODFILIAL = '99') OR (PCPRODUT.CODFILIAL IS NULL))
   AND PCEST.CODFILIAL IN ('1')
   AND NVL(PCEST.QTESTGER, 0) > 0
   AND ((PCPRODUT.OBS2 NOT IN ('FL')) OR (PCPRODUT.OBS2 IS NULL))
-- AND QTINDENIZ > 0
 ORDER BY PCPRODUT.CODPROD
