SELECT SESSAO.CODCLI, SESSAO.USUARIOOS, SESSAO.MAQUINA, SESSAO.CODWINTHOR, SESSAO.USUARIOBD, SESSAO.CODPERFIL
     , NVL(SESSAO.USUARIOBD,'X') ||': '|| NVL(SESSAO.MAQUINA,'X') ||'/'|| NVL(SESSAO.USUARIOOS,0) GRUPO
     , CASE WHEN SESSAO.ROTINA = 000 THEN 'Menu' ELSE SESSAO.ROTINA END ROTINA
  FROM PCCONSUM, ( 
SELECT *
FROM (SELECT PCAUTUSUARIO.CODCLI
           , SESS.OSUSER AS USUARIOOS
           , NVL(SESS.TERMINAL, SESS.MACHINE) AS MAQUINA
           , TO_NUMBER(REGEXP_REPLACE(SUBSTR(SESS.CLIENT_INFO, INSTR(SESS.CLIENT_INFO, ':') + 1, LENGTH(SESS.CLIENT_INFO)),'[^0-9]', '')) AS CODWINTHOR
           , NVL(PCEMPR.USUARIOBD, '[Não Cadastrado]') AS USUARIOBD
           , CASE WHEN INSTR(SESS.CLIENT_INFO, ':') <> 0
                   AND SUBSTR(SESS.CLIENT_INFO, 1, 2) <> '0:'
                  THEN TO_NUMBER(SUBSTR(SESS.CLIENT_INFO, 0, INSTR(SESS.CLIENT_INFO, ':') - 1))
                  ELSE PCEMPR.CODPERFIL
             END CODPERFIL
           , (REGEXP_REPLACE(
                             CASE WHEN NVL(SESS.PROGRAM, SESS.MODULE) LIKE '%PCINFTAB%' THEN
                                  '560' ELSE NVL(SESS.PROGRAM, SUBSTR(SESS.MODULE, 1, INSTR(SESS.MODULE, ' -') - 1)) END,
                             '[^0-9]', '')) AS ROTINA
        FROM SYS.V_$SESS_INFO SESS
           , PCEMPR
           , PCAUTUSUARIO
           , PCCONSUM
       WHERE TO_NUMBER(SUBSTR(SESS.CLIENT_INFO, INSTR(SESS.CLIENT_INFO, ':') + 1, LENGTH(SESS.CLIENT_INFO))) = PCEMPR.MATRICULA(+)
         AND TO_NUMBER(SUBSTR(SESS.CLIENT_INFO, 0, INSTR(SESS.CLIENT_INFO, ':') - 1)) = PCAUTUSUARIO.CODPERFIL(+)
         AND (   (UPPER(SESS.PROGRAM) LIKE 'PCSIS%')
              OR (UPPER(SESS.PROGRAM) LIKE 'PCINF%')
              OR (UPPER(SESS.PROGRAM) LIKE 'PCMIX%')
              OR (UPPER(SESS.PROGRAM) LIKE 'PCVAR%')
              OR (UPPER(SESS.PROGRAM) LIKE 'PCPRI%'))
         AND SESS.STATUS <> 'KILLED'
         AND SESS.ACTION <> '2ª Sessão'
         AND SESS.USERNAME = SYS_CONTEXT('USERENV', 'CURRENT_USER')
         AND INSTR(NVL(SESS.CLIENT_INFO, ' '), ':') > 0
         AND PCAUTUSUARIO.CODCLI = PCCONSUM.CODCLIPC
      UNION
	    SELECT PCAUTUSUARIO.CODCLI
             , GVSESS.OSUSER AS USUARIOOS
             , NVL(GVSESS.TERMINAL, GVSESS.MACHINE) AS MAQUINA
             , TO_NUMBER(REGEXP_REPLACE(SUBSTR(GVSESS.CLIENT_INFO, INSTR(GVSESS.CLIENT_INFO, ':') + 1, LENGTH(GVSESS.CLIENT_INFO)),'[^0-9]', '')) AS CODWINTHOR
             , NVL(PCEMPR.USUARIOBD, '[Não Cadastrado]') AS USUARIOBD
             , CASE WHEN INSTR(GVSESS.CLIENT_INFO, ':') <> 0
                     AND SUBSTR(GVSESS.CLIENT_INFO, 1, 2) <> '0:'
                    THEN TO_NUMBER(SUBSTR(GVSESS.CLIENT_INFO, 0, INSTR(GVSESS.CLIENT_INFO, ':') - 1))
                    ELSE PCEMPR.CODPERFIL
               END CODPERFIL
             , (REGEXP_REPLACE(
                               CASE WHEN NVL(GVSESS.PROGRAM, GVSESS.MODULE) LIKE '%PCINFTAB%' THEN
                                    '560' ELSE NVL(GVSESS.PROGRAM, SUBSTR(GVSESS.MODULE, 1, INSTR(GVSESS.MODULE, ' -') - 1)) END,
                               '[^0-9]', '')) AS ROTINA
          FROM SYS.GV_$SESSION GVSESS
             , PCEMPR
             , PCAUTUSUARIO
             , PCCONSUM
         WHERE TO_NUMBER(SUBSTR(GVSESS.CLIENT_INFO, INSTR(GVSESS.CLIENT_INFO, ':') + 1, LENGTH(GVSESS.CLIENT_INFO))) = PCEMPR.MATRICULA(+)
           AND TO_NUMBER(SUBSTR(GVSESS.CLIENT_INFO, 0, INSTR(GVSESS.CLIENT_INFO, ':') - 1)) = PCAUTUSUARIO.CODPERFIL(+)
           AND (   (UPPER(GVSESS.PROGRAM) LIKE 'PCSIS%')
                OR (UPPER(GVSESS.PROGRAM) LIKE 'PCINF%')
                OR (UPPER(GVSESS.PROGRAM) LIKE 'PCMIX%')
                OR (UPPER(GVSESS.PROGRAM) LIKE 'PCVAR%')
                OR (UPPER(GVSESS.PROGRAM) LIKE 'PCPRI%'))
           AND GVSESS.STATUS <> 'KILLED'
           AND GVSESS.ACTION <> '2ª Sessão'
           AND GVSESS.USERNAME = SYS_CONTEXT('USERENV', 'CURRENT_USER')
           AND INSTR(NVL(GVSESS.CLIENT_INFO, ' '), ':') > 0
           AND PCAUTUSUARIO.CODCLI = PCCONSUM.CODCLIPC
      UNION
      SELECT PCAUTUSUARIO.CODCLI
           , SESSAOCONTINGENCIA.USUARIOOS
           , SESSAOCONTINGENCIA.MAQUINA
           , NVL(SESSAOCONTINGENCIA.CODWINTHOR, NVL(PCEMPR.MATRICULA, 0)) CODWINTHOR
           , NVL(PCEMPR.USUARIOBD, '[Não Cadastrado]') AS USUARIOBD
           , CASE WHEN NVL(PCAUTUSUARIO.CODPERFIL, 0) > 0
                  THEN PCAUTUSUARIO.CODPERFIL
                  ELSE (SELECT CODPERFIL
                          FROM PCLICENCAPRODUTO
                         WHERE ROWNUM = 1)
             END CODPERFIL
           , SESSAOCONTINGENCIA.ROTINA
        FROM (SELECT   NVL(SESSAOWINTHOR.OSUSER, SESSAONULA.USUARIOOS) AS USUARIOOS
                     , NVL(SESSAOWINTHOR.TERMINAL, SESSAONULA.MAQUINA) AS MAQUINA
                     , NVL(SESSAOWINTHOR.CODPERFIL, SESSAONULA.CODPERFIL) AS CODPERFIL
                     , MAX(NVL(SESSAOWINTHOR.CODWINTHOR, SESSAONULA.CODWINTHOR)) AS CODWINTHOR
                     , MAX(REGEXP_REPLACE(NVL(SESSAOWINTHOR.ROTINA, SESSAONULA.ROTINA), '[^0-9]', '')) AS ROTINA
                  FROM (SELECT SYS.V_$SESS_INFO.OSUSER AS USUARIOOS
                             , NVL(SYS.V_$SESS_INFO.TERMINAL, SYS.V_$SESS_INFO.MACHINE) AS MAQUINA
                             , 0 AS CODWINTHOR
                             , 0 CODPERFIL
                             , ' ' PERFIL
                             , NVL(PROGRAM, SUBSTR(SYS.V_$SESS_INFO.MODULE, 1, INSTR(SYS.V_$SESS_INFO.MODULE, ' -') - 1)) AS ROTINA
                          FROM SYS.V_$SESS_INFO
                         WHERE (   (UPPER(PROGRAM) LIKE 'PCSIS%')
                                OR (UPPER(PROGRAM) LIKE 'PCINF%')
                                OR (UPPER(PROGRAM) LIKE 'PCMIX%')
                                OR (UPPER(PROGRAM) LIKE 'PCVAR%')
                                OR (UPPER(PROGRAM) LIKE 'PCPRI%'))
                           AND SYS.V_$SESS_INFO.STATUS <> 'KILLED'
                           AND SYS.V_$SESS_INFO.CLIENT_INFO IS NULL
                           AND SYS.V_$SESS_INFO.ACTION IS NULL
                           AND SYS.V_$SESS_INFO.USERNAME = SYS_CONTEXT('USERENV', 'CURRENT_USER')) SESSAONULA
                     , (SELECT NVL(SESSAO.TERMINAL, SESSAO.MACHINE) AS TERMINAL
                             , SESSAO.OSUSER
                             , TO_NUMBER(SUBSTR(SESSAO.CLIENT_INFO, INSTR(SESSAO.CLIENT_INFO, ':') + 1, LENGTH(SESSAO.CLIENT_INFO))) CODWINTHOR
                             , TO_NUMBER(SUBSTR(SESSAO.CLIENT_INFO, 0, INSTR(SESSAO.CLIENT_INFO, ':') - 1)) CODPERFIL
                             , (NVL(SESSAO.PROGRAM, SUBSTR(SESSAO.MODULE, 1, INSTR(SESSAO.MODULE, ' -') - 1))) AS ROTINA
                          FROM SYS.V_$SESS_INFO SESSAO
                         WHERE SESSAO.USERNAME = SYS_CONTEXT('USERENV', 'CURRENT_USER')
                           AND ((UPPER(SESSAO.PROGRAM) LIKE 'PCSIS%')
                            OR (UPPER(SESSAO.PROGRAM) LIKE 'PCINF%')
                            OR (UPPER(SESSAO.PROGRAM) LIKE 'PCMIX%')
                            OR (UPPER(SESSAO.PROGRAM) LIKE 'PCVAR%')
                            OR (UPPER(SESSAO.PROGRAM) LIKE 'PCPRI%'))
                           AND SESSAO.STATUS <> 'KILLED'
                           AND SESSAO.ACTION <> '2ª Sessão'
                           AND INSTR(NVL(SESSAO.CLIENT_INFO, ' '), ':') > 0) SESSAOWINTHOR
                 WHERE SESSAONULA.USUARIOOS = SESSAOWINTHOR.OSUSER(+)
                   AND SESSAONULA.MAQUINA = SESSAOWINTHOR.TERMINAL(+)
              GROUP BY NVL(SESSAOWINTHOR.OSUSER, SESSAONULA.USUARIOOS)
                     , NVL(SESSAOWINTHOR.TERMINAL, SESSAONULA.MAQUINA) 
                     , NVL(SESSAOWINTHOR.CODPERFIL, SESSAONULA.CODPERFIL)) SESSAOCONTINGENCIA
           , PCEMPR, PCAUTUSUARIO, PCCONSUM
       WHERE SESSAOCONTINGENCIA.CODWINTHOR = PCEMPR.MATRICULA(+)
         AND SESSAOCONTINGENCIA.CODPERFIL = PCAUTUSUARIO.CODPERFIL(+)
         AND PCAUTUSUARIO.CODCLI = PCCONSUM.CODCLIPC
         )
       WHERE 0 = 0

     ) SESSAO 
 WHERE SESSAO.CODPERFIL = 4863
   AND SESSAO.CODCLI = PCCONSUM.CODCLIPC
 ORDER BY NVL(SESSAO.USUARIOOS,'X') || NVL(SESSAO.MAQUINA,'X') || NVL(SESSAO.CODPERFIL,0)
