
WITH PARAMETROS AS 
 (SELECT CODIGO, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('BLOQUEIAVENDAESTPENDENTE', 
                                           PCFILIAL.CODIGO), 
             PCCONSUM.BLOQUEIAVENDAESTPENDENTE) BLOQUEIAVENDAESTPENDENTE, 
         NVL(PCFILIAL.PRECOPOREMBALAGEM, PCCONSUM.PRECOPOREMBALAGEM) PRECOPOREMBALAGEM, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('USAPOLITICACOMERCIALPRODFILIAL'), 
                 'P') USAPOLITICACOMERCIALPRODFILIAL, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('CON_USANEGFORNEC'), 'N') USANEGFORNEC 
    FROM PCFILIAL, 
         PCCONSUM 
   WHERE CODIGO <> '99' 
   AND CODIGO IN('1')
     AND DTEXCLUSAO IS NULL), 
 PCEST2 AS ( 
    SELECT PCEST.DTULTFAT, PCEST.QTESTGER, PCEST.QTRESERV, PCEST.QTBLOQUEADA,PCEST.QTPENDENTE, PCEST.CUSTOULTENT, 
           PCEST.CODFILIAL, PCEST.CODPROD, PCEST.DTULTENT, PCEST.DTULTSAIDA, PCEST.CUSTOFIN, PCEST.CUSTOREP, 
           PCEST.CUSTOREAL, PCEST.CUSTOPROXIMACOMPRA, PCEST.VALORULTENT, PCEST.CUSTOULTPEDCOMPRA, 
           PCEST.CUSTOULTENTFIN, PCEST.CUSTOFORNEC, PCEST.QTULTENT 
    FROM PCEST, PARAMETROS 
    WHERE PCEST.CODFILIAL = PARAMETROS.CODIGO 
    AND PCEST.CODFILIAL IN('1')
) 
 select DISTINCT A.* from (  
SELECT DISTINCT 

       NVL(PCMARCA.CODMARCA,'') MAARCA,      
       NVL(PCMARCA.MARCA,'') MARCA,        
       SUM(((NVL(PCEST2.QTESTGER,0) - NVL(PCEST2.QTRESERV,0) - NVL(PCEST2.QTBLOQUEADA,0) -  (CASE WHEN PARAMETROS.BLOQUEIAVENDAESTPENDENTE = 'S' THEN  NVL(PCEST2.QTPENDENTE, 0)  ELSE 0 END) ))) QTESTOQUE,         
     
       COUNT(PCPRODUT.CODPROD) AS QUANTIDADE,
       
              (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
          (SUM((NVL(PCEST2.QTESTGER,0) - NVL(PCEST2.QTRESERV,0) - NVL(PCEST2.QTBLOQUEADA,0) -  (CASE WHEN PARAMETROS.BLOQUEIAVENDAESTPENDENTE = 'S' THEN  NVL(PCEST2.QTPENDENTE, 0)  ELSE 0 END) ) *  
               NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                  FROM PCEMBALAGEM 
                 WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                   AND (PCEMBALAGEM.CODPROD = PCEST2.CODPROD) 
                   AND PCEMBALAGEM.QTUNIT = 1 
                   AND ROWNUM = 1), 0))) 
         ELSE 
          (SUM((NVL(PCEST2.QTESTGER,0) - NVL(PCEST2.QTRESERV,0) - NVL(PCEST2.QTBLOQUEADA,0) -  (CASE WHEN PARAMETROS.BLOQUEIAVENDAESTPENDENTE = 'S' THEN  NVL(PCEST2.QTPENDENTE, 0)  ELSE 0 END) ) *  
               NVL((SELECT NVL(PCTABPR.PVENDA, 0) 
                  FROM PCTABPR 
                 WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                   AND (PCTABPR.NUMREGIAO = 1)), 0))) 
       END) VLPVENDA 
    

  FROM 
       PCPRODUT, 
       PCEST2, 
       PCFORNEC, 
       PCMARCA, 
       PCLINHAPROD, 
       PCDEPTO, 
       PCSECAO, 
       PCCONSUM, 
       PARAMETROS 
 WHERE PCPRODUT.CODPROD  = PCEST2.CODPROD 
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+) 
   AND PCPRODUT.CODLINHAPROD = PCLINHAPROD.CODLINHA(+) 
   AND PARAMETROS.CODIGO = PCEST2.CODFILIAL 
 AND PCPRODUT.DTEXCLUSAO IS NULL 
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO                                                       
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)                                                      
   AND NVL(PCDEPTO.TIPOMERC, 'XX') NOT IN ('IM','CI')                                     
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC                                                  
   AND (PCPRODUT.CODMARCA IN ( 68 )) 
   AND 'FL' NOT IN NVL((SELECT MAX(DECODE(X.FORALINHA,'S','FL','')) 
                            FROM PCPRODFILIAL X 
                           WHERE X.CODPROD = PCEST2.CODPROD 
                             AND X.CODFILIAL = PCEST2.CODFILIAL ), NVL(PCPRODUT.OBS2,' ' )) 

                             
 --- GROUP
                             
 GROUP BY  
          PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
          PARAMETROS.PRECOPOREMBALAGEM, 
          NVL(PCMARCA.CODMARCA,''),   
          NVL(PCMARCA.MARCA,'')


 ) A 
