SELECT SUM(VLTOTAL) AS VLTOTAL, EXTRACT(MONTH FROM DATA) AS MES,
EXTRACT(YEAR FROM DATA) AS ANO

FROM PCPEDC 
WHERE POSICAO = 'F' AND DTFAT BETWEEN '01-MAY-2020' AND '31-MAY-2020'
AND PCPEDC.DTCANCEL IS NULL
GROUP BY EXTRACT(MONTH FROM DATA), EXTRACT(YEAR FROM DATA);